---
apiVersion: v1
kind: Secret
metadata:
  name: demo-app2-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ozimakov-demo-org/demo-app2-gitops